version: '3.8'

services:
  app:
    build: .  
    image: mouhebzz/events-app  
    ports:
      - "8080:8080"  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/events_db  # Database connection URL
      - SPRING_DATASOURCE_USERNAME=root  # MySQL username
      - SPRING_DATASOURCE_PASSWORD=root  # MySQL password
    depends_on:
      - db  

  db:
    image: mysql:5.7  
    environment:
      MYSQL_ROOT_PASSWORD: root  # Root password for MySQL
      MYSQL_DATABASE: events_db  # Database name to create
    ports:
      - "3306:3306"  

